/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.pr02;

/**
 *
 * @author Aluno
 */
public class Relatorio_Estoque extends javax.swing.JInternalFrame {

    /**
     * Creates new form Relatorio_Prod
     */
    public Relatorio_Estoque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Relatório de Produtos");

        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setVerifyInputWhenFocusTarget(false);

        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Laptop X	", "15", "Eletrônicos", "3.500,00 "},
                {"2", "Fone de Ouvido Y	", "50", "Acessórios", "150,00 "},
                {"3", "Mesa de Escritório Z	", "10", "Móveis", "800,00"},
                {"4", "Smartphone A	", "30", "Eletrônicos", "2.200,00 "},
                {"5", "Cadeira B	", "20", "Móveis", "450,00 "},
                {"6", "Teclado Mecânico C	", "25", "Acessórios", "250,00"},
                {"7", "Monitor D	", "12", "Eletrônicos", "1.200,00 "},
                {"8", "Impressora E	", "8", "Eletrônicos", "600,00 "},
                {"9", "Luminária F	", "40", "Móveis", "120,00 "},
                {"10", "Caderno G	", "100", "Papelaria", "20,00"},
                {"11", "Smartwatch Z4	", "80", "Eletrônicos", "499,00	"},
                {"12", "Geladeira Inox 500L	", "20", "Eletrodomésticos", "3.200,00	"},
                {"13", "Liquidificador 1200W	", "100", "Eletrodomésticos", "299,00	"},
                {"14", "Bolsa de Viagem Grande	", "65", "Acessórios	", "199,90"},
                {"15", "Estabilizador de Tensão 1500VA	", "40", "Eletrônicos	", "159,90"},
                {"16", "Leitor de Cartão SD	", "150", "Eletrônicos	", "79,90"},
                {"17", "Ventilador de Mesa 30cm	", "200", "Eletrodomésticos", "119,90"},
                {"18", "Roteador Wi-Fi Dual Band	", "110", "Eletrônicos	", "229,90"},
                {"19", "Livro \"Como Programar\"	", "300", "Livros", "49,90	"},
                {"20", "Impressora 3D Model X	", "25", "Eletrônicos	", "4.500,00	"}
            },
            new String [] {
                "ID", "Produto", "Quant. Estoque", "Categoria", "Preço"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(20);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Relatório de Produtos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jLabel1)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
